### ISSUE TITLE
".RELEASE" version in pom.xml causes npm build error

### ISSUE THREAD

**Issue by chimericdream** [darrachequesne/sync-pom-version#1]
A lot of maven projects follow the convention of marking their GA releases as something like "1.2.3.RELEASE". But since this doesn't match any formats specified by semver, it causes the npm build to fail.

**Comment by darrachequesne** [comment]
Hi! Do you mind submitting a pull request for your use case?

**Comment by chimericdream** [comment]
Sure thing. Incoming in just a mo'.

**Comment by darrachequesne** [comment]
Great, thanks for the pull request! A last question before merging, should we also handle the other cases:
- `-RELEASE`
- `.RC1`
- `-RC1`
- `-M1`
- ...
Reference: http://www.mojohaus.org/versions-maven-plugin/version-rules.html

**Comment by chimericdream** [comment]
Actually, it looks like we could go a different route. According to the maven docs, the ".RELEASE" or ".RC1" version formats are not valid. The syntax is "#.#.#-QUALIFIER". So we could probably do a handful of replacements:

```
version.replace(/^(\d+(?:\.\d+)*)\.(\D.*)$/, '$1-$2')
    .replace('-RELEASE', '')
    .replace(/^(\d+)(\.\d+)(-.+)?$/, '$1$2.0$3')
    .replace(/^(\d+)(-.+)?$/, '$1.0.0$2');
```

Example JSFiddle: https://jsfiddle.net/hwqgaqmm/9/

That said, since periods aren't considered valid in either Maven or Semver (after the third term), I could see an argument for not merging this at all. Instead, you could add something to the readme along the lines of "If your Maven project doesn't use Semver compatible version numbers, you're a monster. Also, this script won't behave the way you expect."

**Comment by darrachequesne** [comment]
Nice regex! I thought about something a bit simpler, what do you think of:

`.replace(/[\.-](RELEASE|FINAL)$/i, "$'")`

**Comment by chimericdream** [comment]
I'm torn, honestly. On the one hand, it's nice to do the cleanup whenever possible. But on the other hand, if Maven itself uses a version format that is semver compatible (I didn't see it explicitly mentioned), trying to account for all the "wrong" formats could get out of hand.

**Comment by darrachequesne** [comment]
Closed by https://github.com/darrachequesne/sync-pom-version/commit/2e6e1f605babae6f7908dc2f2af0a43e262e0369
